TRIGGERS_STATUS = """
SELECT
    t.name AS trigger_adi,
    OBJECT_NAME(t.parent_id) AS tablo,
    CASE t.is_disabled WHEN 0 THEN 'AKTIF' WHEN 1 THEN 'KAPALI' END AS durum,
    t.create_date AS olusturma_tarihi,
    t.modify_date AS son_degisiklik
FROM sys.triggers t
WHERE t.name IN (
    'LG_INVOICE_DEL_321_01','LG_CHANGELOG_DEL_321','LG_SERILOTN_DEL_321_01',
    'LG_CLCARD_DEL_321','LG_STFCHCK_DEL_321_01','LG_STLINECK_DEL_321_01',
    'LG_SLLINECK_DEL_321_01','LG_BNFICHE_DEL_321_01','LG_BNFLINECK_DEL_321_01',
    'LG_BNCARD_DEL_321','LG_CLFICHE_DEL_321_01','LG_CLFLINECK_DEL_321_01',
    'LG_CSCARD_DEL_321_01','LG_CSTRANS_DEL_321_01','LG_CSROLL_DEL_321_01',
    'LG_PAYTRANS_DEL_321_01','LG_KSLINECK_DEL_321_01','LG_EMUHACCK_DEL_321'
)
ORDER BY t.name;
"""

DELETION_COUNTS = """
SELECT 'INVOICE' AS kategori, COUNT(*) AS sayi FROM [dbo].[L_CAPIDEL_INVLOG]
UNION ALL SELECT 'STFICHE', COUNT(*) FROM [dbo].[L_CAPIDEL_SFLOG]
UNION ALL SELECT 'STLINE', COUNT(*) FROM [dbo].[L_CAPIDEL_STLLOG]
UNION ALL SELECT 'SLTRANS', COUNT(*) FROM [dbo].[L_CAPIDEL_SLTLOG]
UNION ALL SELECT 'SERILOTN', COUNT(*) FROM [dbo].[L_CAPIDEL_SERLOG]
UNION ALL SELECT 'CHANGELOG', COUNT(*) FROM [dbo].[L_CAPIDEL_CLLOG]
UNION ALL SELECT 'CLCARD', COUNT(*) FROM [dbo].[L_CAPIDEL_CCLOG]
UNION ALL SELECT 'BNFICHE', COUNT(*) FROM [dbo].[L_CAPIDEL_BNFLOG]
UNION ALL SELECT 'BNFLINE', COUNT(*) FROM [dbo].[L_CAPIDEL_BNLLOG]
UNION ALL SELECT 'BNCARD', COUNT(*) FROM [dbo].[L_CAPIDEL_BNCLOG]
UNION ALL SELECT 'CLFICHE', COUNT(*) FROM [dbo].[L_CAPIDEL_CFFLOG]
UNION ALL SELECT 'CLFLINE', COUNT(*) FROM [dbo].[L_CAPIDEL_CFLLOG]
UNION ALL SELECT 'CSCARD', COUNT(*) FROM [dbo].[L_CAPIDEL_CSCLOG]
UNION ALL SELECT 'CSTRANS', COUNT(*) FROM [dbo].[L_CAPIDEL_CSTLOG]
UNION ALL SELECT 'CSROLL', COUNT(*) FROM [dbo].[L_CAPIDEL_CSRLOG]
UNION ALL SELECT 'PAYTRANS', COUNT(*) FROM [dbo].[L_CAPIDEL_PAYLOG]
UNION ALL SELECT 'KSLINES', COUNT(*) FROM [dbo].[L_CAPIDEL_KSLLOG]
UNION ALL SELECT 'EMUHACC', COUNT(*) FROM [dbo].[L_CAPIDEL_EMLOG];
"""

RECENT_STFICHE = """SELECT TOP {limit} FORMAT(sf.CAPIPOLICYDATE,'dd.MM.yyyy HH:mm:ss') AS zaman,sf.CAPIPOLICYUSER AS hesap,sf.CAPIPOLICYHOST AS bilgisayar,sf.CAPIPOLICYAPP AS uygulama,sf.FICHENO AS fis_no,sf.TRCODE AS tr_kodu,FORMAT(sf.DATE_,'dd.MM.yyyy') AS fis_tarihi FROM [dbo].[L_CAPIDEL_SFLOG] sf ORDER BY sf.CAPIPOLICYDATE DESC;"""
RECENT_STLINE = """SELECT TOP {limit} FORMAT(stl.CAPIPOLICYDATE,'dd.MM.yyyy HH:mm:ss') AS zaman,stl.CAPIPOLICYUSER AS hesap,stl.CAPIPOLICYHOST AS bilgisayar,stl.CAPIPOLICYAPP AS uygulama,stl.STFICHEREF AS fis_ref,stl.STOCKREF AS malzeme_ref,stl.AMOUNT AS miktar_kg,stl.TRCODE AS tr_kodu,stl.LINETYPE AS satir_tipi FROM [dbo].[L_CAPIDEL_STLLOG] stl ORDER BY stl.CAPIPOLICYDATE DESC;"""
RECENT_PAYTRANS = """SELECT TOP {limit} FORMAT(p.CAPIPOLICYDATE,'dd.MM.yyyy HH:mm:ss') AS zaman,p.CAPIPOLICYUSER AS hesap,p.CAPIPOLICYHOST AS bilgisayar,p.CAPIPOLICYAPP AS uygulama,p.TOTAL AS tutar,p.TRCODE AS tr_kodu,FORMAT(p.DATE_,'dd.MM.yyyy') AS odeme_tarihi FROM [dbo].[L_CAPIDEL_PAYLOG] p ORDER BY p.CAPIPOLICYDATE DESC;"""
RECENT_INVOICE = """SELECT TOP {limit} FORMAT(inv.CAPIPOLICYDATE,'dd.MM.yyyy HH:mm:ss') AS zaman,inv.CAPIPOLICYUSER AS hesap,inv.CAPIPOLICYHOST AS bilgisayar,inv.CAPIPOLICYIP AS ip_adresi,inv.CAPIPOLICYAPP AS uygulama,inv.FICHESSION AS fatura_no,inv.NETTOTAL AS tutar,inv.TRCODE AS tr_kodu,FORMAT(inv.DATE_,'dd.MM.yyyy') AS fatura_tarihi,inv.CLIENTREF AS cari_ref FROM [dbo].[L_CAPIDEL_INVLOG] inv ORDER BY inv.CAPIPOLICYDATE DESC;"""
RECENT_SLTRANS = """SELECT TOP {limit} FORMAT(slt.CAPIPOLICYDATE,'dd.MM.yyyy HH:mm:ss') AS zaman,slt.CAPIPOLICYUSER AS hesap,slt.CAPIPOLICYHOST AS bilgisayar,slt.CAPIPOLICYAPP AS uygulama,slt.STTRANSREF AS stok_hareket_ref,slt.SLREF AS lot_ref,slt.AMOUNT AS miktar_kg,FORMAT(slt.DATE_,'dd.MM.yyyy') AS hareket_tarihi FROM [dbo].[L_CAPIDEL_SLTLOG] slt ORDER BY slt.CAPIPOLICYDATE DESC;"""
RECENT_SERILOTN = """SELECT TOP {limit} FORMAT(s.CAPIPOLICYDATE,'dd.MM.yyyy HH:mm:ss') AS zaman,s.CAPIPOLICYUSER AS hesap,s.CAPIPOLICYHOST AS bilgisayar,s.CAPIPOLICYAPP AS uygulama,s.LREF,s.CODE,s.NAME FROM [dbo].[L_CAPIDEL_SERLOG] s ORDER BY s.CAPIPOLICYDATE DESC;"""
RECENT_CHANGELOG = """SELECT TOP {limit} FORMAT(c.CAPIPOLICYDATE,'dd.MM.yyyy HH:mm:ss') AS zaman,c.CAPIPOLICYUSER AS hesap,c.CAPIPOLICYHOST AS bilgisayar,c.CAPIPOLICYAPP AS uygulama,c.LREF,c.RECORDREF,c.USERNR,c.OPERATION,c.FORMID,c.DESCRIPTION FROM [dbo].[L_CAPIDEL_CLLOG] c ORDER BY c.CAPIPOLICYDATE DESC;"""
RECENT_CLCARD = """SELECT TOP {limit} FORMAT(c.CAPIPOLICYDATE,'dd.MM.yyyy HH:mm:ss') AS zaman,c.CAPIPOLICYUSER AS hesap,c.CAPIPOLICYHOST AS bilgisayar,c.CAPIPOLICYAPP AS uygulama,c.LREF,c.CODE,c.DEFINITION_ FROM [dbo].[L_CAPIDEL_CCLOG] c ORDER BY c.CAPIPOLICYDATE DESC;"""
RECENT_BNFICHE = """SELECT TOP {limit} FORMAT(b.CAPIPOLICYDATE,'dd.MM.yyyy HH:mm:ss') AS zaman,b.CAPIPOLICYUSER AS hesap,b.CAPIPOLICYHOST AS bilgisayar,b.CAPIPOLICYAPP AS uygulama,b.FICHENO,b.NETTOTAL AS tutar,b.TRCODE AS tr_kodu,FORMAT(b.DATE_,'dd.MM.yyyy') AS tarih FROM [dbo].[L_CAPIDEL_BNFLOG] b ORDER BY b.CAPIPOLICYDATE DESC;"""
RECENT_BNFLINE = """SELECT TOP {limit} FORMAT(b.CAPIPOLICYDATE,'dd.MM.yyyy HH:mm:ss') AS zaman,b.CAPIPOLICYUSER AS hesap,b.CAPIPOLICYHOST AS bilgisayar,b.CAPIPOLICYAPP AS uygulama,b.BNFICHEREF,b.BNACCREF,b.AMOUNT AS tutar,b.TRCODE AS tr_kodu,FORMAT(b.DATE_,'dd.MM.yyyy') AS tarih FROM [dbo].[L_CAPIDEL_BNLLOG] b ORDER BY b.CAPIPOLICYDATE DESC;"""
RECENT_BNCARD = """SELECT TOP {limit} FORMAT(b.CAPIPOLICYDATE,'dd.MM.yyyy HH:mm:ss') AS zaman,b.CAPIPOLICYUSER AS hesap,b.CAPIPOLICYHOST AS bilgisayar,b.CAPIPOLICYAPP AS uygulama,b.LREF,b.CODE,b.DEFINITION_ FROM [dbo].[L_CAPIDEL_BNCLOG] b ORDER BY b.CAPIPOLICYDATE DESC;"""
RECENT_CLFICHE = """SELECT TOP {limit} FORMAT(c.CAPIPOLICYDATE,'dd.MM.yyyy HH:mm:ss') AS zaman,c.CAPIPOLICYUSER AS hesap,c.CAPIPOLICYHOST AS bilgisayar,c.CAPIPOLICYAPP AS uygulama,c.FICHENO,c.NETTOTAL AS tutar,c.TRCODE AS tr_kodu,FORMAT(c.DATE_,'dd.MM.yyyy') AS tarih FROM [dbo].[L_CAPIDEL_CFFLOG] c ORDER BY c.CAPIPOLICYDATE DESC;"""
RECENT_CLFLINE = """SELECT TOP {limit} FORMAT(c.CAPIPOLICYDATE,'dd.MM.yyyy HH:mm:ss') AS zaman,c.CAPIPOLICYUSER AS hesap,c.CAPIPOLICYHOST AS bilgisayar,c.CAPIPOLICYAPP AS uygulama,c.CLFICHEREF,c.CLCARDREF,c.AMOUNT AS tutar,c.CREDIT,c.TRCODE AS tr_kodu,FORMAT(c.DATE_,'dd.MM.yyyy') AS tarih FROM [dbo].[L_CAPIDEL_CFLLOG] c ORDER BY c.CAPIPOLICYDATE DESC;"""
RECENT_CSCARD = """SELECT TOP {limit} FORMAT(c.CAPIPOLICYDATE,'dd.MM.yyyy HH:mm:ss') AS zaman,c.CAPIPOLICYUSER AS hesap,c.CAPIPOLICYHOST AS bilgisayar,c.CAPIPOLICYAPP AS uygulama,c.LREF,c.CODE,c.DEFINITION_,c.AMOUNT AS tutar,c.OWN_ FROM [dbo].[L_CAPIDEL_CSCLOG] c ORDER BY c.CAPIPOLICYDATE DESC;"""
RECENT_CSTRANS = """SELECT TOP {limit} FORMAT(c.CAPIPOLICYDATE,'dd.MM.yyyy HH:mm:ss') AS zaman,c.CAPIPOLICYUSER AS hesap,c.CAPIPOLICYHOST AS bilgisayar,c.CAPIPOLICYAPP AS uygulama,c.CSREF,c.AMOUNT AS tutar,c.TRCODE AS tr_kodu,FORMAT(c.DATE_,'dd.MM.yyyy') AS tarih FROM [dbo].[L_CAPIDEL_CSTLOG] c ORDER BY c.CAPIPOLICYDATE DESC;"""
RECENT_CSROLL = """SELECT TOP {limit} FORMAT(c.CAPIPOLICYDATE,'dd.MM.yyyy HH:mm:ss') AS zaman,c.CAPIPOLICYUSER AS hesap,c.CAPIPOLICYHOST AS bilgisayar,c.CAPIPOLICYAPP AS uygulama,c.CSREF,c.AMOUNT AS tutar,c.TRCODE AS tr_kodu,FORMAT(c.DATE_,'dd.MM.yyyy') AS tarih FROM [dbo].[L_CAPIDEL_CSRLOG] c ORDER BY c.CAPIPOLICYDATE DESC;"""
RECENT_KSLINES = """SELECT TOP {limit} FORMAT(k.CAPIPOLICYDATE,'dd.MM.yyyy HH:mm:ss') AS zaman,k.CAPIPOLICYUSER AS hesap,k.CAPIPOLICYHOST AS bilgisayar,k.CAPIPOLICYAPP AS uygulama,k.LREF,k.AMOUNT AS tutar,k.TRCODE AS tr_kodu,FORMAT(k.DATE_,'dd.MM.yyyy') AS tarih FROM [dbo].[L_CAPIDEL_KSLLOG] k ORDER BY k.CAPIPOLICYDATE DESC;"""
RECENT_EMUHACC = """SELECT TOP {limit} FORMAT(e.CAPIPOLICYDATE,'dd.MM.yyyy HH:mm:ss') AS zaman,e.CAPIPOLICYUSER AS hesap,e.CAPIPOLICYHOST AS bilgisayar,e.CAPIPOLICYAPP AS uygulama,e.LREF,e.CODE,e.DEFINITION_ FROM [dbo].[L_CAPIDEL_EMLOG] e ORDER BY e.CAPIPOLICYDATE DESC;"""

TABLE_QUERIES = {
    "INVOICE": RECENT_INVOICE, "STFICHE": RECENT_STFICHE, "STLINE": RECENT_STLINE,
    "SLTRANS": RECENT_SLTRANS, "SERILOTN": RECENT_SERILOTN, "CHANGELOG": RECENT_CHANGELOG,
    "CLCARD": RECENT_CLCARD, "BNFICHE": RECENT_BNFICHE, "BNFLINE": RECENT_BNFLINE,
    "BNCARD": RECENT_BNCARD, "CLFICHE": RECENT_CLFICHE, "CLFLINE": RECENT_CLFLINE,
    "CSCARD": RECENT_CSCARD, "CSTRANS": RECENT_CSTRANS, "CSROLL": RECENT_CSROLL,
    "PAYTRANS": RECENT_PAYTRANS, "KSLINES": RECENT_KSLINES, "EMUHACC": RECENT_EMUHACC,
}

CHANGELOG_COMPARISON = """
SELECT '320_KAYNAK' AS tablo, COUNT(*) AS sayi FROM [TIGERDB].[dbo].[LG_320_CHANGELOG] WITH (NOLOCK)
UNION ALL SELECT '320_YEDEK', COUNT(*) FROM [VeribanLocalDB].[dbo].[LG_320_CHANGELOG_YEDEK]
UNION ALL SELECT '321_KAYNAK', COUNT(*) FROM [TIGERDB].[dbo].[LG_321_CHANGELOG] WITH (NOLOCK)
UNION ALL SELECT '321_YEDEK', COUNT(*) FROM [VeribanLocalDB].[dbo].[LG_321_CHANGELOG_YEDEK];
"""

SNAPSHOT_COMPARISON = """
SELECT
    SNAP.TABLENAME AS tablo, SNAP.ROWCOUNT_ AS snapshot_kayit, SNAP.MAXREF AS snapshot_maxref,
    FORMAT(SNAP.SNAPDATE, 'dd.MM.yyyy HH:mm') AS snapshot_zamani,
    CASE SNAP.TABLENAME
        WHEN 'LG_321_01_INVOICE' THEN (SELECT COUNT(*) FROM [dbo].[LG_321_01_INVOICE] WITH(NOLOCK))
        WHEN 'LG_321_01_STFICHE' THEN (SELECT COUNT(*) FROM [dbo].[LG_321_01_STFICHE] WITH(NOLOCK))
        WHEN 'LG_321_01_STLINE' THEN (SELECT COUNT(*) FROM [dbo].[LG_321_01_STLINE] WITH(NOLOCK))
        WHEN 'LG_321_01_SLTRANS' THEN (SELECT COUNT(*) FROM [dbo].[LG_321_01_SLTRANS] WITH(NOLOCK))
        WHEN 'LG_321_01_SERILOTN' THEN (SELECT COUNT(*) FROM [dbo].[LG_321_01_SERILOTN] WITH(NOLOCK))
        WHEN 'LG_321_01_PAYTRANS' THEN (SELECT COUNT(*) FROM [dbo].[LG_321_01_PAYTRANS] WITH(NOLOCK))
        WHEN 'LG_321_01_CLFLINE' THEN (SELECT COUNT(*) FROM [dbo].[LG_321_01_CLFLINE] WITH(NOLOCK))
        WHEN 'LG_321_01_BNFLINE' THEN (SELECT COUNT(*) FROM [dbo].[LG_321_01_BNFLINE] WITH(NOLOCK))
        WHEN 'LG_321_01_BNFICHE' THEN (SELECT COUNT(*) FROM [dbo].[LG_321_01_BNFICHE] WITH(NOLOCK))
        WHEN 'LG_321_CHANGELOG' THEN (SELECT COUNT(*) FROM [dbo].[LG_321_CHANGELOG] WITH(NOLOCK))
    END AS guncel_kayit
FROM [dbo].[L_CAPIPOLICY_SNAP] SNAP ORDER BY SNAP.TABLENAME;
"""

JOBS_STATUS = """
SELECT
    j.name AS job_adi,
    CASE j.enabled WHEN 1 THEN 'AKTIF' ELSE 'KAPALI' END AS durum,
    CASE jh.run_status WHEN 0 THEN 'BASARISIZ' WHEN 1 THEN 'BASARILI' WHEN 2 THEN 'TEKRAR DENEME' WHEN 3 THEN 'IPTAL' WHEN 4 THEN 'DEVAM EDIYOR' END AS son_calisma_durumu,
    STUFF(STUFF(RIGHT('000000'+CAST(jh.run_time AS VARCHAR),6),3,0,':'),6,0,':') AS saat,
    CONVERT(DATE,CAST(jh.run_date AS VARCHAR),112) AS tarih
FROM msdb.dbo.sysjobs j
LEFT JOIN (SELECT job_id,run_status,run_date,run_time,ROW_NUMBER() OVER (PARTITION BY job_id ORDER BY run_date DESC,run_time DESC) AS rn FROM msdb.dbo.sysjobhistory WHERE step_id=0) jh ON j.job_id=jh.job_id AND jh.rn=1
WHERE j.name IN ('syspolicy_purge_history','LG_CapiDailyAudit') ORDER BY j.name;
"""

COMPUTER_DISTRIBUTION = """
SELECT CAPIPOLICYHOST AS bilgisayar,COUNT(*) AS toplam_silme,MIN(CAPIPOLICYDATE) AS ilk_silme,MAX(CAPIPOLICYDATE) AS son_silme
FROM (
    SELECT CAPIPOLICYHOST,CAPIPOLICYDATE FROM [dbo].[L_CAPIDEL_SFLOG]
    UNION ALL SELECT CAPIPOLICYHOST,CAPIPOLICYDATE FROM [dbo].[L_CAPIDEL_STLLOG]
    UNION ALL SELECT CAPIPOLICYHOST,CAPIPOLICYDATE FROM [dbo].[L_CAPIDEL_SLTLOG]
    UNION ALL SELECT CAPIPOLICYHOST,CAPIPOLICYDATE FROM [dbo].[L_CAPIDEL_PAYLOG]
    UNION ALL SELECT CAPIPOLICYHOST,CAPIPOLICYDATE FROM [dbo].[L_CAPIDEL_INVLOG]
    UNION ALL SELECT CAPIPOLICYHOST,CAPIPOLICYDATE FROM [dbo].[L_CAPIDEL_SERLOG]
    UNION ALL SELECT CAPIPOLICYHOST,CAPIPOLICYDATE FROM [dbo].[L_CAPIDEL_BNFLOG]
    UNION ALL SELECT CAPIPOLICYHOST,CAPIPOLICYDATE FROM [dbo].[L_CAPIDEL_BNLLOG]
    UNION ALL SELECT CAPIPOLICYHOST,CAPIPOLICYDATE FROM [dbo].[L_CAPIDEL_CFFLOG]
    UNION ALL SELECT CAPIPOLICYHOST,CAPIPOLICYDATE FROM [dbo].[L_CAPIDEL_CFLLOG]
    UNION ALL SELECT CAPIPOLICYHOST,CAPIPOLICYDATE FROM [dbo].[L_CAPIDEL_CSTLOG]
) AS t GROUP BY CAPIPOLICYHOST ORDER BY toplam_silme DESC;
"""

DAILY_TREND = """
SELECT CAST(CAPIPOLICYDATE AS DATE) AS gun,COUNT(*) AS silme_sayisi
FROM (
    SELECT CAPIPOLICYDATE FROM [dbo].[L_CAPIDEL_SFLOG]
    UNION ALL SELECT CAPIPOLICYDATE FROM [dbo].[L_CAPIDEL_STLLOG]
    UNION ALL SELECT CAPIPOLICYDATE FROM [dbo].[L_CAPIDEL_SLTLOG]
    UNION ALL SELECT CAPIPOLICYDATE FROM [dbo].[L_CAPIDEL_PAYLOG]
    UNION ALL SELECT CAPIPOLICYDATE FROM [dbo].[L_CAPIDEL_INVLOG]
    UNION ALL SELECT CAPIPOLICYDATE FROM [dbo].[L_CAPIDEL_SERLOG]
    UNION ALL SELECT CAPIPOLICYDATE FROM [dbo].[L_CAPIDEL_BNFLOG]
    UNION ALL SELECT CAPIPOLICYDATE FROM [dbo].[L_CAPIDEL_BNLLOG]
    UNION ALL SELECT CAPIPOLICYDATE FROM [dbo].[L_CAPIDEL_CFFLOG]
    UNION ALL SELECT CAPIPOLICYDATE FROM [dbo].[L_CAPIDEL_CFLLOG]
    UNION ALL SELECT CAPIPOLICYDATE FROM [dbo].[L_CAPIDEL_CSTLOG]
) AS t GROUP BY CAST(CAPIPOLICYDATE AS DATE) ORDER BY gun;
"""

RECENT_ALL_DELETIONS = """
SELECT TOP {limit} * FROM (
    SELECT TOP {limit} FORMAT(CAPIPOLICYDATE,'dd.MM.yyyy HH:mm:ss') AS zaman,CAPIPOLICYDATE AS sira,CAPIPOLICYUSER AS hesap,CAPIPOLICYHOST AS bilgisayar,'STFICHE' AS tablo,FICHENO AS detay FROM [dbo].[L_CAPIDEL_SFLOG]
    UNION ALL SELECT TOP {limit} FORMAT(CAPIPOLICYDATE,'dd.MM.yyyy HH:mm:ss'),CAPIPOLICYDATE,CAPIPOLICYUSER,CAPIPOLICYHOST,'STLINE',CAST(STFICHEREF AS VARCHAR) FROM [dbo].[L_CAPIDEL_STLLOG]
    UNION ALL SELECT TOP {limit} FORMAT(CAPIPOLICYDATE,'dd.MM.yyyy HH:mm:ss'),CAPIPOLICYDATE,CAPIPOLICYUSER,CAPIPOLICYHOST,'SLTRANS',CAST(STTRANSREF AS VARCHAR) FROM [dbo].[L_CAPIDEL_SLTLOG]
    UNION ALL SELECT TOP {limit} FORMAT(CAPIPOLICYDATE,'dd.MM.yyyy HH:mm:ss'),CAPIPOLICYDATE,CAPIPOLICYUSER,CAPIPOLICYHOST,'INVOICE',FICHESSION FROM [dbo].[L_CAPIDEL_INVLOG]
    UNION ALL SELECT TOP {limit} FORMAT(CAPIPOLICYDATE,'dd.MM.yyyy HH:mm:ss'),CAPIPOLICYDATE,CAPIPOLICYUSER,CAPIPOLICYHOST,'PAYTRANS',CAST(TOTAL AS VARCHAR) FROM [dbo].[L_CAPIDEL_PAYLOG]
    UNION ALL SELECT TOP {limit} FORMAT(CAPIPOLICYDATE,'dd.MM.yyyy HH:mm:ss'),CAPIPOLICYDATE,CAPIPOLICYUSER,CAPIPOLICYHOST,'BNFICHE',FICHENO FROM [dbo].[L_CAPIDEL_BNFLOG]
    UNION ALL SELECT TOP {limit} FORMAT(CAPIPOLICYDATE,'dd.MM.yyyy HH:mm:ss'),CAPIPOLICYDATE,CAPIPOLICYUSER,CAPIPOLICYHOST,'CLFICHE',FICHENO FROM [dbo].[L_CAPIDEL_CFFLOG]
    UNION ALL SELECT TOP {limit} FORMAT(CAPIPOLICYDATE,'dd.MM.yyyy HH:mm:ss'),CAPIPOLICYDATE,CAPIPOLICYUSER,CAPIPOLICYHOST,'SERILOTN',CODE FROM [dbo].[L_CAPIDEL_SERLOG]
    UNION ALL SELECT TOP {limit} FORMAT(CAPIPOLICYDATE,'dd.MM.yyyy HH:mm:ss'),CAPIPOLICYDATE,CAPIPOLICYUSER,CAPIPOLICYHOST,'CHANGELOG',DESCRIPTION FROM [dbo].[L_CAPIDEL_CLLOG]
) AS tum ORDER BY sira DESC;
"""
